spring:
  config:
    import:
      - kafka/kafka-config.yml
      - mongodb/mongodb-config.yml

car_service:
  url: 'http://se-car-service-part2/api/v1/'

currency-converter:
  default-currency: 'USD'
